[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Lura Skye", email = "fuyukaii@proton.me"},
]
license = {text = "GPL-3.0-or-later"}
requires-python = ">=3.13"
dependencies = [
    "attrs>=23.2.0",
    "cattrs>=23.2.3",
    "prettyprinter>=0.18.0",
    "jinja2>=3.1.4",
    "pillow>=10.3.0",
    "inflection>=0.5.1",
    "unidecode>=1.3.8",
    "rtoml>=0.10.0",
    "tqdm>=4.66.4",
    "typing-extensions>=4.11.0",
    "rich>=13.7.1",
    "tomli-w>=1.2.0",
    "sortedcontainers>=2.4.0",
    "rgcompiler @ git+ssh://git@codeberg.org/Fuyukai/rgcompiler.git",
    "structlog>=25.1.0",
]
name = "reborn-rebalance"
version = "0.7.0"
description = "Pokémon Reborn rebalancing mod"
readme = "README.rst"

[project.scripts]
into-pbs = "reborn_rebalance.building.to_pbs:build_to_pbs"
into-toml = "reborn_rebalance.building.to_toml:import_to_toml"
ruby-unmarshal = "reborn_rebalance.unmarshal:main"
build-web = "reborn_rebalance.building.web:main"
copy-compiled-files = "reborn_rebalance.scripts.copy_changes:main"
resave-data = "reborn_rebalance.scripts.resave:main"
validate-catalog = "reborn_rebalance.scripts.validate:do_extended_validation"
update-moves = "reborn_rebalance.scripts.update_moves:main"
resync-tms = "reborn_rebalance.scripts.resync_tms:main"
find-new-forms = "reborn_rebalance.scripts.find_new_forms:main"
parse-ruby-movelist = "reborn_rebalance.scripts.parse_ruby_movelist:main"
"dump-map-scripts" = "reborn_rebalance.scripts.dump_map_scripts:main"
"clear-empty-evs" = "reborn_rebalance.scripts.clear_empty_evs:main"

[dependency-groups]
dev = [
    "ruff>=0.9.3",
    "pyright>=1.1.392.post0",
    "sortedcontainers-stubs>=2.4.2",
]

[tool.pyright]
pythonVersion = "3.13"
include = ["src"]
typeCheckingMode = "strict"

reportImplicitOverride = "warning"
reportUnusedVariable = false
reportIncompatibleVariableOverride = false
reportPrivateUsage = false

[tool.ruff]
target-version = "py313"
respect-gitignore = true
src = ["src/reborn_rebalance"]
line-length = 100
output-format = "full"
preview = true

[tool.ruff.lint]
select = [
    "RUF",
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "Q",
    "YTT",
    "PYI",
    "SIM",
    "RET",
    "PERF",
    "PIE",
    "SIM",
    "C4",
    "FA",
    "ICN",
    "PYI",
    "PT",
    "RET",

    # specific docstring rules
    "D201",
    "D204",
    "D211",
    "D419", # less ugly docstrings
]
ignore = [
    "W291",
    "W293",
    "W391",
    "UP038",
    "PIE807"
]

[tool.ruff.lint.per-file-ignores]
"tests/test_*" = ["D"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pdm.build]
includes = [
    "src/reborn_rebalance",
]
