[tool.poetry]
name = "reborn-rebalance"
version = "0.1.0"
description = ""
authors = ["Lura Skye <l@veriny.tf>"]
readme = "README.rst"
packages = [{include = "reborn_rebalance", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
ruamel-yaml = "^0.17.32"
attrs = "^23.1.0"
cattrs = "^23.1.2"
prettyprinter = "^0.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
